### ISSUE TITLE
Unable to save Live Stripe Keys

### ISSUE THREAD

**Issue by CameronGilroy** [nexusmerchants/wp-orderforms-stripe#2]
Currently, the regx doesn't support the saving of live keys. I have forked and tested a fix. https://github.com/CameronGilroy/wp-orderforms-stripe/commit/58d1097749376b4a647eaf6a8487ab282f9a98df

The current regx is `(s|r)k_(test_)?[A-Za-z0-9]{8,}` and it should be `sk_(test_|live_)?[A-Za-z0-9]{8,}`

**Comment by agewriter** [comment]
Hi Cameron, thanks for spotting this! Do you want to create a PR?

**Comment by CameronGilroy** [comment]
Here is the pull request https://github.com/nexusmerchants/wp-orderforms-stripe/pull/3
